language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
before_install:
  - gem update bundler
gemfile:
 - gemfiles/rails_3_2.gemfile
 - gemfiles/rails_3_2_stable.gemfile
 - gemfiles/rails_4_0.gemfile
 - gemfiles/rails_4_0_stable.gemfile
 - gemfiles/rails_4_1.gemfile
 - gemfiles/rails_4_1_stable.gemfile
 - gemfiles/rails_master.gemfile
branches:
  only:
    - master
