language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
before_install:
  - gem update bundler
gemfile:
 - gemfiles/rails_3_2.gemfile
 - gemfiles/rails_4_0.gemfile
 - gemfiles/rails_4_1.gemfile
 - gemfiles/rails_4_2.gemfile
 - gemfiles/rails_5_0.gemfile
 - gemfiles/rails_master.gemfile
matrix:
  exclude:
  - rvm: 2.0.0
    gemfile: gemfiles/rails_5_0.gemfile
  - rvm: 2.0.0
    gemfile: gemfiles/rails_master.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_5_0.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/rails_master.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4_0.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4_1.gemfile
  - rvm: 2.4.0
    gemfile: gemfiles/rails_4_2.gemfile
